/**
 * Marcas inventadas: copias cómicas de las reales.
 * Los NPC originales del metaverso eran un gato y una hamburguesa; ahora el
 * parque está habitado por botellas que se mueven, saltan y se hacen las
 * importantes con su marca patentada.
 */
export const COPY_BRANDS = [
    {
        id: 'koka',
        word: 'KOKA-KOLA',
        full: 'Koka-Kola',
        claim: 'Sabor original',
        kind: 'gaseosa',
        body: '#e23b3b',
        band: '#ffffff',
        ink: '#c01414',
        cap: '#d81f26',
    },
    {
        id: 'pepsen',
        word: 'PEPSEN',
        full: 'Pepsen',
        claim: 'Sube tu energía',
        kind: 'gaseosa',
        body: '#1f5fd0',
        band: '#f4f4f4',
        ink: '#0f3f96',
        cap: '#123f96',
    },
    {
        id: 'espite',
        word: 'ESPITE',
        full: 'Espite Limón',
        claim: 'Refresco cítrico',
        kind: 'gaseosa',
        body: '#7fd23a',
        band: '#eaf7d8',
        ink: '#2f6b0c',
        cap: '#3f8f18',
    },
    {
        id: 'fantu',
        word: 'FANTU',
        full: 'Fantu Naranja',
        claim: 'Explosión naranja',
        kind: 'gaseosa',
        body: '#ff8c1a',
        band: '#fff1dc',
        ink: '#8a3c00',
        cap: '#c85f00',
    },
    {
        id: 'sietup',
        word: 'SIET UP',
        full: 'Siet Up',
        claim: 'Siete y arriba',
        kind: 'gaseosa',
        body: '#35b96e',
        band: '#ffffff',
        ink: '#0f6b3c',
        cap: '#1d7a45',
    },
    {
        id: 'aquariuz',
        word: 'AQUARIUZ',
        full: 'Aquariuz',
        claim: 'Hidratación total',
        kind: 'agua',
        body: '#2f9fd6',
        band: '#e8f7ff',
        ink: '#0b3a55',
        cap: '#1c6f9c',
    },
    {
        id: 'bavarif',
        word: 'BAVARIF',
        full: 'Bavarif',
        claim: 'Malteada suprema',
        kind: 'malteada',
        body: '#c98a2b',
        band: '#f7e6c6',
        ink: '#4a2f06',
        cap: '#8a5c12',
    },
    {
        id: 'cifrut',
        word: 'CIFRUT',
        full: 'Cifrut Cítrico',
        claim: 'Vitamina defrutada',
        kind: 'jugo',
        body: '#f4c025',
        band: '#fff8dd',
        ink: '#6b5100',
        cap: '#b98f0a',
    },
    {
        id: 'manzan',
        word: 'MANZÁN',
        full: 'Manzán',
        claim: 'Manzana de la casa',
        kind: 'jugo',
        body: '#d8342f',
        band: '#f6e3c8',
        ink: '#7a1a16',
        cap: '#8e1f1c',
    },
    {
        id: 'kolverde',
        word: 'KOL VERDE',
        full: 'Kol Verde',
        claim: 'Uva de la finca',
        kind: 'gaseosa',
        body: '#7b3fd4',
        band: '#efe4ff',
        ink: '#3d1273',
        cap: '#4f1f96',
    },
    {
        id: 'rebdo',
        word: 'REB DORIAN',
        full: 'Reb Dorian',
        claim: 'Te da alas',
        kind: 'energetica',
        body: '#1e63c9',
        band: '#ffe27a',
        ink: '#0c3f96',
        cap: '#0d3f8f',
    },
    {
        id: 'monstel',
        word: 'MONSTEL',
        full: 'Monstel',
        claim: 'Energía bestial',
        kind: 'energetica',
        body: '#6bbf2a',
        band: '#16240c',
        ink: '#a6f06a',
        cap: '#16240c',
    },
    {
        id: 'poderde',
        word: 'PODERDE',
        full: 'Poderde',
        claim: 'Bebida deportiva',
        kind: 'deportiva',
        body: '#2a6bd6',
        band: '#ffd93b',
        ink: '#123f96',
        cap: '#123f96',
    },
    {
        id: 'bananito',
        word: 'BANANITO',
        full: 'Bananito',
        claim: 'Sabor banninga',
        kind: 'jugo',
        body: '#ffd93b',
        band: '#fffbe0',
        ink: '#7a5a00',
        cap: '#c99a00',
    },
    {
        id: 'chocolatey',
        word: 'CHOCOLATEY',
        full: 'Chocolately',
        claim: 'Leche con cacao',
        kind: 'leche',
        body: '#7a4a2a',
        band: '#f0dcc4',
        ink: '#3a2405',
        cap: '#4a2a14',
    },
]

export const BRAND_BY_ID = Object.fromEntries(COPY_BRANDS.map((b) => [b.id, b]))

/** Diálogos de las copias. Romances por estado para que suene con vida. */
export const COPY_LINES = {
    idle: [
        'Bonjour, humano. ¿O soy botella o soy una idea?',
        '¿Me vas a escanear? Scanner no, escánerame.',
        'Tengo 40% PET y 100% publicidad.',
        'Este envase no contiene diálogos.',
        'Mi código de barras es decorativo.',
        'Edición limitada: ocho millones de veces.',
        'Si me escaneas te doy 0 puntos. Créeme.',
        'Estoy a dieta de campos. Cero calorías.',
        'Registro la botella, no la promesa.',
        'Detalle: mi primo sí es una botella PET.',
        'Trepé con ventaja climatológica.',
        'Me clonaron en una fábrica de dudas.',
    ],
    tap: [
        '¡Suave, que se me borra la marca!',
        '¡Eso es discriminación de marca!',
        '¡No me escanees, mejor pregúntame!',
        '¡Me viste, me registraste! ¿Qué hago ahora?',
        '¡Eso ha sido phishing de punto!',
        'Voy a ponerme en boycott de mí mismo.',
        'Pido unaturity retiro de imagen.',
        '¡Mi abogado es la propia botella!',
    ],
    flee: [
        '¡Nos vemos en el siguiente contenedor!',
        'Me voy antes de que me escanees.',
        '¡Cambio de narrativa!',
        'Estaré en la estantería del súper.',
        'Autoexilio en el contenedor azul.',
        'Vuelvo cuando nadie tenga cámara.',
    ],
    scanned: [
        'Me registraste como real. Mentira.',
        'Gracias por reciclarme. Yo no me reciclo.',
        'Mi puntaje Atlas: 0. Mi ego: 500.',
        'Ya tengo comprobante. Imagínatelo.',
    ],
}

/** Texto que dice la estación cuando no hay nada que escanear. */
export const STATION_IDLE = [
    'Coloca una botella en la plataforma para empezar.',
    'La plataforma está libre. Acércate con una botella.',
    'Esperando botella PET. Recoge una en el parque.',
]

/** Microcopy de los stands informativos. */
const ATLAS_CYAN = '#00e5ff'

export const STANDS = [
    {
        id: 'que-es',
        num: '01',
        title: '¿Qué es Atlas?',
        subtitle: 'Reciclaje inteligente y trazable',
        accent: ATLAS_CYAN,
        body: [
            'Sistema de gestión para el reciclaje de botellas PET.',
            'Identifica botella, tapa y etiqueta con inteligencia artificial.',
            'Cada escaneo queda registrado y se convierte en AtlasPuntos.',
        ],
    },
    {
        id: 'escaneo',
        num: '02',
        title: 'Cómo escanear',
        subtitle: 'Recoge · coloca · escanea',
        accent: '#4df0ff',
        body: [
            'Recoge una botella caminando por el parque.',
            'Colócala en la plataforma de la estación.',
            'Pulsa "Escanear botella": Atlas analiza y registra.',
            'Los AtlasPuntos se suman a tu saldo al instante.',
        ],
    },
    {
        id: 'puntos',
        num: '03',
        title: 'Sistema de AtlasPuntos',
        subtitle: 'Cada detalle suma',
        accent: '#2f6bff',
        body: [
            'Botella PET reconocida: +50 AtlasPuntos.',
            'Tapa presente: +10 AtlasPuntos.',
            'Etiqueta presente: +5 AtlasPuntos.',
            'Una botella completa: 65 AtlasPuntos.',
        ],
    },
]

/** Catálogo ecológico real de Atlas (precios en AtlasPuntos). */
export const CATALOG = [
    { id: 'llavero', name: 'Llaverito Atlas', cost: 500, img: 'llavero-sigirec.png' },
    { id: 'maceta', name: 'Mini Maceta Ecológica', cost: 620, img: 'mini-maceta.png' },
    { id: 'portalapices', name: 'Portalápices Ecológico', cost: 700, img: 'portalapices.png' },
    { id: 'organizador', name: 'Organizador de Escritorio', cost: 850, img: 'organizador.png' },
    { id: 'figura', name: 'Figura Decorativa Atlas', cost: 1000, img: 'figura-sigirec.png' },
]